Repository Team-GulBi/Backend_V2, pull requests merged in 2025-08, with the labels that each got.

#7 [Refactor] 상품 수정 API 전략패턴 및 템플릿 메소드로 변경
  .gitignore
  src/main/java/com/gulbi/Backend/domain/rental/product/controller/ProductController.java
  src/main/java/com/gulbi/Backend/domain/rental/product/dto/product/request/ProductImageDeleteRequest.java
  src/main/java/com/gulbi/Backend/domain/rental/product/dto/product/request/register/NewProductImageRequest.java
  src/main/java/com/gulbi/Backend/domain/rental/product/dto/product/request/update/MainImageUrlUpdateRequest.java
  src/main/java/com/gulbi/Backend/domain/rental/product/dto/product/request/update/ProductCategoryUpdateRequest.java
  src/main/java/com/gulbi/Backend/domain/rental/product/dto/product/request/update/ProductCategoryUpdateRequestDto.java
  src/main/java/com/gulbi/Backend/domain/rental/product/dto/product/request/update/productTextUpdateRequest.java
  src/main/java/com/gulbi/Backend/domain/rental/product/dto/product/update/ProductContentUpdateCommand.java
  src/main/java/com/gulbi/Backend/domain/rental/product/dto/product/update/ProductImageInfoUpdateDto.java
  src/main/java/com/gulbi/Backend/domain/rental/product/dto/product/update/ProductImageUpdateCommand.java
  src/main/java/com/gulbi/Backend/domain/rental/product/dto/product/update/ProductInfoUpdateDto.java
  src/main/java/com/gulbi/Backend/domain/rental/product/entity/Product.java
  src/main/java/com/gulbi/Backend/domain/rental/product/repository/ImageRepository.java
  src/main/java/com/gulbi/Backend/domain/rental/product/repository/ProductRepository.java
  src/main/java/com/gulbi/Backend/domain/rental/product/service/category/CategoryBusinessService.java
  src/main/java/com/gulbi/Backend/domain/rental/product/service/category/CategoryBusinessServiceImpl.java
  src/main/java/com/gulbi/Backend/domain/rental/product/service/image/ImageCrudService.java
  src/main/java/com/gulbi/Backend/domain/rental/product/service/image/ImageCrudServiceImpl.java
  src/main/java/com/gulbi/Backend/domain/rental/product/service/image/ImageService.java
  src/main/java/com/gulbi/Backend/domain/rental/product/service/image/ImageServiceImpl.java
  src/main/java/com/gulbi/Backend/domain/rental/product/service/image/strategy/AbstractImageUpdateStrategy.java
  src/main/java/com/gulbi/Backend/domain/rental/product/service/image/strategy/ImageDeleteStrategy.java
  src/main/java/com/gulbi/Backend/domain/rental/product/service/image/strategy/ImageUpdateStrategy.java
  src/main/java/com/gulbi/Backend/domain/rental/product/service/image/strategy/ImageUploadStrategy.java
  src/main/java/com/gulbi/Backend/domain/rental/product/service/image/strategy/MainImageFileUpdateStrategy.java
  src/main/java/com/gulbi/Backend/domain/rental/product/service/image/strategy/MainImageUrlUpdateStrategy.java
  src/main/java/com/gulbi/Backend/domain/rental/product/service/product/ProductService.java
  src/main/java/com/gulbi/Backend/domain/rental/product/service/product/ProductServiceImpl.java
  src/main/java/com/gulbi/Backend/domain/rental/product/service/product/crud/ProductCrudService.java
  src/main/java/com/gulbi/Backend/domain/rental/product/service/product/crud/ProductCrudServiceImpl.java
  src/main/java/com/gulbi/Backend/domain/rental/product/service/product/register/ProductRegistrationService.java
  src/main/java/com/gulbi/Backend/domain/rental/product/service/product/register/ProductRegistrationServiceImpl.java
  src/main/java/com/gulbi/Backend/domain/rental/product/service/product/update/ProductUpdateServiceImpl.java
  src/main/java/com/gulbi/Backend/domain/rental/product/service/product/update/ProductUpdatingService.java
  src/main/java/com/gulbi/Backend/domain/rental/product/service/product/update/Strategy/ProductCategoryUpdateStrategy.java
  src/main/java/com/gulbi/Backend/domain/rental/product/service/product/update/Strategy/ProductTextInfoUpdateStrategy.java
  src/main/java/com/gulbi/Backend/domain/rental/product/service/product/update/Strategy/ProductUpdateStrategy.java
Labels: refactor

#8 [Refactor]
  src/main/java/com/gulbi/Backend/domain/contract/controller/ContractController.java
  src/main/java/com/gulbi/Backend/domain/contract/dto/ContractCreateDto.java
  src/main/java/com/gulbi/Backend/domain/contract/dto/ContractCreateRequest.java
  src/main/java/com/gulbi/Backend/domain/contract/service/ContractService.java
  src/main/java/com/gulbi/Backend/domain/rental/application/controller/ProductApplicationController.java
  src/main/java/com/gulbi/Backend/domain/rental/application/dto/ApplicationCreateDto.java
  src/main/java/com/gulbi/Backend/domain/rental/application/dto/ApplicationCreateRequest.java
  src/main/java/com/gulbi/Backend/domain/rental/application/entity/Application.java
  src/main/java/com/gulbi/Backend/domain/rental/application/service/ApplicationService.java
Labels: refactor

#10 [Feat] 예약 조회 API
  src/main/java/com/gulbi/Backend/domain/contract/controller/ContractController.java
  src/main/java/com/gulbi/Backend/domain/contract/dto/ContractResponseDto.java
  src/main/java/com/gulbi/Backend/domain/contract/repository/ContractRepository.java
  src/main/java/com/gulbi/Backend/domain/contract/service/ContractService.java
  src/main/java/com/gulbi/Backend/domain/rental/application/controller/ProductApplicationController.java
  src/main/java/com/gulbi/Backend/domain/rental/application/dto/ApplicationCalendarResponse.java
  src/main/java/com/gulbi/Backend/domain/rental/application/dto/ApplicationDayResponse.java
  src/main/java/com/gulbi/Backend/domain/rental/application/dto/ApplicationStatusDetailResponse.java
  src/main/java/com/gulbi/Backend/domain/rental/application/dto/ApplicationStatusProjection.java
  src/main/java/com/gulbi/Backend/domain/rental/application/dto/ApplicationStatusResponse.java
  src/main/java/com/gulbi/Backend/domain/rental/application/repository/ApplicationRepository.java
  src/main/java/com/gulbi/Backend/domain/rental/application/service/ApplicationService.java
Labels: feat

#14 [Refactor] User, Profile Refactoring
  src/main/java/com/gulbi/Backend/domain/rental/product/dto/product/response/ProductDetailResponseDto.java
  src/main/java/com/gulbi/Backend/domain/rental/product/service/product/search/ProductSearchServiceImpl.java
  src/main/java/com/gulbi/Backend/domain/rental/review/repository/ReviewRepository.java
  src/main/java/com/gulbi/Backend/domain/user/controller/AuthController.java
  src/main/java/com/gulbi/Backend/domain/user/controller/ProfileController.java
  src/main/java/com/gulbi/Backend/domain/user/dto/LoginRequest.java
  src/main/java/com/gulbi/Backend/domain/user/dto/ProfileCreateCommand.java
  src/main/java/com/gulbi/Backend/domain/user/dto/ProfileRequestDto.java
  src/main/java/com/gulbi/Backend/domain/user/dto/ProfileResponse.java
  src/main/java/com/gulbi/Backend/domain/user/dto/ProfileResponseDto.java
  src/main/java/com/gulbi/Backend/domain/user/dto/ProfileUpdateCommand.java
  src/main/java/com/gulbi/Backend/domain/user/dto/ProfileUpdateRequest.java
  src/main/java/com/gulbi/Backend/domain/user/dto/RegisterCommand.java
  src/main/java/com/gulbi/Backend/domain/user/dto/RegisterRequest.java
  src/main/java/com/gulbi/Backend/domain/user/entity/Profile.java
  src/main/java/com/gulbi/Backend/domain/user/entity/User.java
  src/main/java/com/gulbi/Backend/domain/user/repository/ProfileRepoService.java
  src/main/java/com/gulbi/Backend/domain/user/repository/UserRepoService.java
  src/main/java/com/gulbi/Backend/domain/user/service/ProfileService.java
  src/main/java/com/gulbi/Backend/domain/user/service/UserService.java
  src/main/java/com/gulbi/Backend/global/test/Controller/DummyController.java
  src/main/java/com/gulbi/Backend/global/test/ProductDataInitService.java
  src/main/java/com/gulbi/Backend/global/test/ProfileInitService.java
  src/main/java/com/gulbi/Backend/global/util/JwtUtil.java
Labels: refactor

#30 [Refactor] Template 응답 수정
  src/main/java/com/gulbi/Backend/domain/contract/application/controller/ProductApplicationController.java
  src/main/java/com/gulbi/Backend/domain/contract/application/service/ApplicationService.java
  src/main/java/com/gulbi/Backend/domain/contract/contract/controller/ContractController.java
  src/main/java/com/gulbi/Backend/domain/contract/contract/dto/TemplateResponse.java
  src/main/java/com/gulbi/Backend/domain/contract/contract/entity/ContractFactory.java
  src/main/java/com/gulbi/Backend/domain/contract/contract/entity/ContractTemplate.java
  src/main/java/com/gulbi/Backend/domain/contract/contract/entity/ContractTemplateFactory.java
  src/main/java/com/gulbi/Backend/domain/contract/contract/repository/ContractTemplateRepository.java
  src/main/java/com/gulbi/Backend/domain/contract/contract/service/ContractService.java
  src/main/java/com/gulbi/Backend/domain/contract/contract/service/ContractTemplateRepoService.java
  src/main/java/com/gulbi/Backend/domain/contract/contract/service/ContractTemplateService.java
  src/main/java/com/gulbi/Backend/domain/rental/product/entity/Product.java
  src/main/java/com/gulbi/Backend/domain/rental/product/factory/ProductFactory.java
  src/main/java/com/gulbi/Backend/domain/rental/product/repository/ProductRepository.java
  src/main/java/com/gulbi/Backend/domain/rental/product/service/product/crud/ProductRepoJpaService.java
  src/main/java/com/gulbi/Backend/domain/rental/product/service/product/crud/ProductRepoService.java
  src/main/java/com/gulbi/Backend/domain/rental/product/service/product/register/ProductRegistrationServiceImpl.java
Labels: refactor

#37 hotfix: 빌드 에러 해결
  src/main/java/com/gulbi/Backend/domain/user/entity/User.java
  src/main/java/com/gulbi/Backend/global/error/GlobalExceptionHandler.java
Labels: bug

#38 fix: 허용 엔드포인트 수정
  src/main/java/com/gulbi/Backend/global/config/SecurityConfig.java
Labels: bug

#43 [refactor] 상품 삭제 시 제약조건 예외 처리
  src/main/java/com/gulbi/Backend/domain/contract/contract/repository/ContractTemplateRepository.java
  src/main/java/com/gulbi/Backend/domain/contract/contract/service/ContractTemplateRepoService.java
  src/main/java/com/gulbi/Backend/domain/rental/product/entity/Product.java
  src/main/java/com/gulbi/Backend/domain/rental/product/repository/ImageRepository.java
  src/main/java/com/gulbi/Backend/domain/rental/product/service/image/ImageRepoJpaService.java
  src/main/java/com/gulbi/Backend/domain/rental/product/service/image/ImageRepoService.java
  src/main/java/com/gulbi/Backend/domain/rental/product/service/product/delete/ProductDeleteServiceImpl.java
  src/main/java/com/gulbi/Backend/domain/rental/review/repository/ReviewRepository.java
  src/main/java/com/gulbi/Backend/domain/rental/review/service/ReviewRepoJpaService.java
  src/main/java/com/gulbi/Backend/domain/rental/review/service/ReviewRepoService.java
Labels: refactor

#45 [Refactor] 상품 등록시 Image nullable 허용
  src/main/java/com/gulbi/Backend/domain/rental/product/controller/ProductController.java
  src/main/java/com/gulbi/Backend/domain/rental/product/dto/ProductRegisterCommand.java
  src/main/java/com/gulbi/Backend/domain/rental/product/dto/ProductTextUpdateRequest.java
  src/main/java/com/gulbi/Backend/domain/rental/product/entity/Product.java
  src/main/java/com/gulbi/Backend/domain/rental/product/repository/ProductRepository.java
  src/main/java/com/gulbi/Backend/domain/rental/product/service/product/crud/ProductRepoJpaService.java
  src/main/java/com/gulbi/Backend/domain/rental/product/service/product/register/ProductRegistrationServiceImpl.java
Labels: refactor

#54 [Refactor]
  src/main/java/com/gulbi/Backend/domain/contract/application/service/ApplicationService.java
  src/main/java/com/gulbi/Backend/domain/rental/product/dto/ProductDetailResponse.java
  src/main/java/com/gulbi/Backend/domain/rental/product/entity/Product.java
  src/main/java/com/gulbi/Backend/domain/rental/product/repository/ProductRepository.java
  src/main/java/com/gulbi/Backend/domain/rental/product/service/product/crud/ProductRepoJpaService.java
  src/main/java/com/gulbi/Backend/domain/rental/product/service/product/crud/ProductRepoService.java
  src/main/java/com/gulbi/Backend/domain/rental/product/service/product/search/ProductSearchServiceImpl.java
  src/main/java/com/gulbi/Backend/domain/rental/recommandation/service/personal/strategy/latest/LatestRecommendationStrategy.java
Labels: refactor
